name: Website checks
 
on:

  pull_request:

    branches: [main]
 
jobs:
  branch-name-check:
    name: Branch name check

    runs-on: ubuntu-latest

    steps:
      - name: Check branch name
        run: |
          BRANCH="${{ github.head_ref }}"

          if [[ ! "$BRANCH" =~ ^Task/[A-Z]+-[0-9]+$ ]]; then
            echo "❌ Invalid branch name: $BRANCH"
            echo "Expected format: Task/TaskId. Example: Task/SCRUM-01"
            exit 1
          fi

          echo "✅ Branch name is valid: $BRANCH"
  html-check:

    name: HTML check

    runs-on: ubuntu-latest
 
    steps:

      - name: Get project files

        uses: actions/checkout@v4
 
      - name: Check that index.html exists

        run: test -f index.html
 
 
  css-check:

    name: CSS check

    runs-on: ubuntu-latest
 
    steps:

      - name: Get project files

        uses: actions/checkout@v4
 
      - name: Check that style.css exists and is not empty

        run: test -f CSS/style.css
 
